# Generated by Django 3.2.9 on 2021-12-16 01:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_customer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Profile',
        ),
    ]
