# Generated by Django 3.2.9 on 2021-12-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Profile',
            new_name='profile',
        ),
    ]
