# Generated by Django 3.2.9 on 2021-12-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_profile_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
