# Generated by Django 3.2.9 on 2021-12-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='description',
        ),
    ]
