# Generated by Django 4.0.2 on 2022-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_profile_balance_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('vegtables', 'Vegetables'), ('meat_and_poultry', 'Meat and Poultry'), ('fish_and_seafood', 'Fish and Seafood')], max_length=100)),
            ],
        ),
    ]
