# Generated by Django 4.0.2 on 2022-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
